[package]
name = "fastgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
rand = "0.8.3"
smartcore = "0.2.0"
sys-info = "0.9.1"
